#!/usr/bin/env bash
# phasekit installer.
#
#   curl -fsSL https://raw.githubusercontent.com/porkchop/phasekit/master/install.sh | bash
#
# Installs a canonical phasekit clone (the single source of truth for running
# and upgrading) into ~/.local/share/phasekit, builds an isolated venv for its
# one dependency (pyyaml), and drops a `phasekit` launcher on PATH. It does NOT
# touch any project — enrich a project explicitly afterwards with `phasekit
# adopt`. Re-running updates an existing install to the latest release tag.
#
# Trust: this pipes a script to your shell. To inspect first:
#   curl -fsSL https://raw.githubusercontent.com/porkchop/phasekit/master/install.sh -o install.sh
#   less install.sh && bash install.sh
#
# Overridable via environment:
#   PHASEKIT_URL   git remote to clone (default: the public GitHub repo)
#   PHASEKIT_HOME  install location    (default: ${XDG_DATA_HOME:-~/.local/share}/phasekit)
#   PHASEKIT_BIN   launcher directory  (default: ~/.local/bin)
#   PHASEKIT_REF   pin a tag/branch    (default: latest v* release tag, else default branch)
set -euo pipefail

PHASEKIT_URL="${PHASEKIT_URL:-https://github.com/porkchop/phasekit.git}"
PHASEKIT_HOME="${PHASEKIT_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/phasekit}"
PHASEKIT_BIN="${PHASEKIT_BIN:-$HOME/.local/bin}"
PHASEKIT_REF="${PHASEKIT_REF:-}"

say()  { printf 'phasekit-install: %s\n' "$*"; }
die()  { printf 'phasekit-install: error: %s\n' "$*" >&2; exit 1; }

# --- 1. prerequisites -------------------------------------------------------
command -v git     >/dev/null 2>&1 || die "git is required but not found."
command -v python3 >/dev/null 2>&1 || die "python3 is required but not found."
python3 -c 'import venv, ensurepip' >/dev/null 2>&1 \
  || die "python3 venv support is missing. Install it (e.g. 'apt install python3-venv') and re-run."

# --- 2. clone or update -----------------------------------------------------
if [[ -d "$PHASEKIT_HOME/.git" ]]; then
  say "updating existing install at $PHASEKIT_HOME"
  git -C "$PHASEKIT_HOME" fetch --tags --quiet origin
elif [[ -e "$PHASEKIT_HOME" ]]; then
  die "$PHASEKIT_HOME exists but is not a git checkout; move it aside and re-run."
else
  say "cloning $PHASEKIT_URL → $PHASEKIT_HOME"
  mkdir -p "$(dirname "$PHASEKIT_HOME")"
  # Full history (no --depth) so --check-version can use commit ancestry.
  git clone --quiet "$PHASEKIT_URL" "$PHASEKIT_HOME"
fi

# --- 3. resolve and check out the release ref -------------------------------
ref="$PHASEKIT_REF"
if [[ -z "$ref" ]]; then
  ref="$(git -C "$PHASEKIT_HOME" tag -l 'v*' | sort -V | tail -n1)"
fi
if [[ -z "$ref" ]]; then
  # No release tags yet: fall back to the remote's default branch.
  ref="$(git -C "$PHASEKIT_HOME" symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null \
         | sed 's#^origin/##')"
  ref="${ref:-master}"
  say "no release tags found; tracking '$ref'"
  git -C "$PHASEKIT_HOME" checkout --quiet "$ref"
  git -C "$PHASEKIT_HOME" pull --quiet --ff-only origin "$ref" || true
else
  say "checking out release $ref"
  git -C "$PHASEKIT_HOME" checkout --quiet "$ref"
fi

# --- 4. isolated venv with the one dependency (pyyaml) ----------------------
if [[ ! -x "$PHASEKIT_HOME/.venv/bin/python" ]]; then
  say "creating venv at $PHASEKIT_HOME/.venv"
  python3 -m venv "$PHASEKIT_HOME/.venv"
fi
say "installing dependencies (pyyaml)"
"$PHASEKIT_HOME/.venv/bin/pip" install --quiet --upgrade pip pyyaml \
  || die "failed to install pyyaml into the venv (network required for a fresh install)."

# --- 5. launcher shim on PATH -----------------------------------------------
mkdir -p "$PHASEKIT_BIN"
shim="$PHASEKIT_BIN/phasekit"
cat > "$shim" <<EOF
#!/usr/bin/env bash
# phasekit launcher (generated by install.sh). Relocate by editing PHASEKIT_HOME.
export PHASEKIT_PYTHON="$PHASEKIT_HOME/.venv/bin/python"
exec "$PHASEKIT_HOME/scripts/phasekit.sh" "\$@"
EOF
chmod +x "$shim"

version="$(git -C "$PHASEKIT_HOME" describe --tags --always 2>/dev/null || echo "$ref")"
say "installed phasekit $version → $shim"

# --- 6. PATH advice + next steps --------------------------------------------
case ":$PATH:" in
  *":$PHASEKIT_BIN:"*) : ;;
  *) say "NOTE: $PHASEKIT_BIN is not on your PATH. Add it, e.g.:"
     printf '       echo '\''export PATH="%s:$PATH"'\'' >> ~/.bashrc && source ~/.bashrc\n' "$PHASEKIT_BIN" ;;
esac

cat <<EOF

Done. Next:
  cd your-project && phasekit adopt          # enrich an existing repo
  cd new-project  && phasekit bootstrap      # greenfield (optionally: phasekit bootstrap <profile>)

Other commands:
  phasekit check-version     # is a newer scaffold release out?
  phasekit upgrade           # re-provision this project against the current scaffold
  phasekit self-update       # move this phasekit install to the latest release tag
EOF
